/*
 * This file was automatically generated by EvoSuite
 * Mon Oct 15 19:24:26 GMT 2018
 */

package com.github.cseppento.gradle.evosuite.testprojects.simple;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import com.github.cseppento.gradle.evosuite.testprojects.simple.SimpleObjectSut;
import java.util.SortedSet;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, useJEE = true) 
public class SimpleObjectSut_ESTest extends SimpleObjectSut_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      SimpleObjectSut simpleObjectSut0 = new SimpleObjectSut(125L);
      simpleObjectSut0.guessDivisor(125L);
      simpleObjectSut0.check();
      assertEquals(125L, simpleObjectSut0.getValue());
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      SimpleObjectSut simpleObjectSut0 = new SimpleObjectSut((-930L));
      // Undeclared exception!
      try { 
        simpleObjectSut0.guessDivisor(1939L);
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // 1939 is not a divisor of 930
         //
         verifyException("com.github.cseppento.gradle.evosuite.testprojects.simple.SimpleObjectSut", e);
      }
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      SimpleObjectSut simpleObjectSut0 = new SimpleObjectSut(1562L);
      // Undeclared exception!
      try { 
        simpleObjectSut0.guessDivisor((-1L));
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // Invalid divisor: -1
         //
         verifyException("com.github.cseppento.gradle.evosuite.testprojects.simple.SimpleObjectSut", e);
      }
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      SimpleObjectSut simpleObjectSut0 = new SimpleObjectSut(125L);
      simpleObjectSut0.guessDivisor(125L);
      // Undeclared exception!
      try { 
        simpleObjectSut0.guessDivisor(125L);
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // 125 is already added as a divisor of 125
         //
         verifyException("com.github.cseppento.gradle.evosuite.testprojects.simple.SimpleObjectSut", e);
      }
  }

  @Test(timeout = 4000)
  public void test4()  throws Throwable  {
      SimpleObjectSut simpleObjectSut0 = new SimpleObjectSut(125L);
      SortedSet<Long> sortedSet0 = simpleObjectSut0.getDivisors();
      assertFalse(sortedSet0.contains(125L));
  }

  @Test(timeout = 4000)
  public void test5()  throws Throwable  {
      SimpleObjectSut simpleObjectSut0 = new SimpleObjectSut((-1L));
      String string0 = simpleObjectSut0.toString();
      assertEquals("SimpleObjectSut of 1 with divisors []", string0);
  }

  @Test(timeout = 4000)
  public void test6()  throws Throwable  {
      SimpleObjectSut simpleObjectSut0 = new SimpleObjectSut(125L);
      long long0 = simpleObjectSut0.getValue();
      assertEquals(125L, long0);
  }
}
